### ISSUE TITLE
stdout

### ISSUE THREAD

**Issue by cylott** [ingve/ql-icon#1]
Wow, this is fantastic! Thank you so much @ingve for taking the time to do this. I've done a bit of testing, and so far, so good.

My first question is, would it be possible to pass the result to stdout? I am assuming the quality flag does nothing on a PNG. In this case, I will pass the result to something like [pngquant](https://github.com/kornelski/pngquant). It would be great to do this in a single command without an intermediary file.

**Comment by ingve** [comment]
That does sound very useful, and I think it should be possible by using `CGImageDestinationCreateWithData` instead of `CGImageDestinationCreateWithURL`.
