### ISSUE TITLE
Generic file icons

### ISSUE THREAD

**Issue by cylott** [ingve/ql-icon#2]
My next question deals with files that have a generic icon. I've been using [QLTool](https://github.com/trishume/QLTool), which is rather old and resource-intensive. QLTool always seems to generate an icon, regardless of whether or not the source has a Quicklook icon. It makes previews of custom icons (pasted from the Finder Get Info pane), app bundles, folders, etc.

For example, this does not generate an icon, because "file" uses a generic document icon:
>user$ touch file
>user$ ql-icon --input=file --output=myicon.png --verbose
>width: 512, height: 512, input: file, output: myicon.png, type: public.png, quality: 1.00

I'm not exactly sure how QLTool works its magic, but as ql-icon uses the same methods as qlmanage, and qlmanage doesn't seem to want to make an icon for these sorts of files, I'm assuming it is not possible. Thought I'd ask though.

**Comment by ingve** [comment]
I think it's possible, but not by just using `QLThumbnailImageCreate`, it will require some additional fallback logic.

`NSWorkspace` has an `iconForFile:` method that can be used to get generic (per extension/"file-type") icons (and probably custom icons as well?)

**Comment by cylott** [comment]
> I think it's possible, but not by just using `QLThumbnailImageCreate`, it will require some additional fallback logic.
> 
> `NSWorkspace` has an `iconForFile:` method that can be used to get generic (per extension/"file-type") icons (and probably custom icons as well?)

Hi @ingve, I've been using ql-icon without issue in my project, and its been working wonderfully. As the test app I posted a while back shows, it makes icons in a fraction of the time of other tools. Thank you!

Looking into the question of "generic" icons, it does seem that the other project I mentioned is using this fallback. It does indeed retrieve whatever icon is present in the Finder, including custom icons.
https://github.com/trishume/QLTool/blob/3f47125914b5c6bc319faca54be92a4458896197/QLTool/NSImage%2BQuickLook.m#L45

From my superficial understanding of things, it seems ql-icon is using QLThumbnailImageCreate to create the image, whereas this other project (which is over 10 years old) is creating a new NSImage, and then copying over whichever data it needs (either from QLThumbnailImageCreate or from iconForFile). Is there a way this type of approach could be used in ql-icon, or would it require a different approach?

Thanks again for your generosity!

**Comment by cylott** [comment]
Digging into this a bit deeper, it seems iconForFile is a Cocoa method. From what I can tell, iconForFile is the only way to reliably retrieve the icon that the Finder sees, no matter what the file. There is some discussion of how to do this with Swift, but this produces very different results (it is essentially only for generic file icons based on the file's UTI):
https://indiestack.com/2018/05/icon-for-file-with-uikit/

I tried to implement some of the code from this project:
https://github.com/socketwiz/IconForFileType/blob/c471145ba406211046e0e3a846e6bceff7d06681/IconForFileTypeAppDelegate.m#L41

But this requires including the Cocoa frameworks. I tried adding
>#include <Cocoa/Cocoa.h>

and
>-framework Cocoa

To the Makefile but I'm getting this error when I try to make:

>/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:503:1: fatal error: expected identifier or '(' @class NSString, Protocol;

It seems all the code needs to do is create an image, fill it with iconForFile, and output that as a file. I'm a bit stuck though, being so new to C and the various Apple frameworks.

**Comment by ingve** [comment]
I've had an experimental branch using `iconForFile` for a while, but I want to restructure the supporting code (argument parsing, image saving etc.) to get ql-icon and ql-thumbnail back in sync.

**Comment by cylott** [comment]
> I've had an experimental branch using `iconForFile` for a while, but I want to restructure the supporting code (argument parsing, image saving etc.) to get ql-icon and ql-thumbnail back in sync.

Thanks for the update! I'm glad to hear iconForFile might make its way into qt-icon. Are you thinking it will be a fallback if QuickLook doesn't produce anything for a given file?

If its not too much trouble I'd love to take a look at a dev branch or a PR for this. My application is currently using ql-icon first, and then QLTool as a fallback, but QLTool is very slow and I'm generating millions and millions of icons.

socketwiz/IconForFileType is a good tool to demonstrate iconForFile but I'm having trouble refactoring this code into something that will work as a simple command line tool, the way qt-icon does.

**Comment by cylott** [comment]
> I've had an experimental branch using `iconForFile` for a while, but I want to restructure the supporting code (argument parsing, image saving etc.) to get ql-icon and ql-thumbnail back in sync.

Hi @ingve. It took me 10 hours, but I managed to figure out how to import the cocoa libs by passing the -ObjC clang flag, and to create an NSImage with iconForFile. I'm lost, however, when it comes to creating the CGImageRef that image_for_file produces. This is what I've got:

    image = image_for_file(filename, width, height);
    if (!image) {
        NSImage *icon = [[NSWorkspace sharedWorkspace] iconForFile:[NSString stringWithUTF8String:filename]];
		NSRect iconRect = NSMakeRect(0, 0, icon.size.width, icon.size.height);
		CGImageRef *image [icon CGImageForProposedRect:&iconRect context:NULL hints:nil];
    }

If you have a chance, I'd really love to see the experimental branch you mentioned!

**Comment by ingve** [comment]
#5 has initial support for generic icons.

**Comment by cylott** [comment]
> #5 has initial support for generic icons.

Thank you so much for letting me test out this branch!

Here's an updated `IconTester.app`, which can be used for quick drag and drop testing:
[IconTester.app.zip](https://github.com/ingve/ql-icon/files/3749936/IconTester.app.zip)

I'll put this to the test with a few million files and report back.

Initial thoughts:
• In my tests, IconForFile generates 2x resources (request a 512 icon, and you will get a 1024 icon). This is probably because I'm using a "retina" display. This is different from QuickLook which will always produce the size requested regardless of display pixel density.
• It would be cool if the exit code could reflect the tool used (0 for failure, 1 for QuickLook, 2 for IconForFile, something like that)

For now I'll pass files to `ql-icon`, and if it doesn't produce anything, cut the resolution in half and send to `icon`.

Again, my deepest thanks.

**Comment by ingve** [comment]
Closed by #5
