### ISSUE TITLE
Specify image size by multiplier

### ISSUE THREAD

**Issue by cylott** [ingve/ql-icon#3]
Is there a way to specify icon size by multiplier rather than pixel dimensions? This often produces different icons:
https://github.com/ingve/ql-thumbnail/issues/5#issuecomment-502410286

**Comment by cylott** [comment]
Also, just wanted to say again how grateful I am to you for sharing this code. I ask these questions out of curiosity, not complaint. I'm working on an open source file catalogue project and this will be immensely helpful. I will continue to test with different scenarios/systems and report back.

**Comment by ingve** [comment]
The different icons depending on size, and the somewhat strange "effects" that are added to icons (page curls were hot... in the mid-90s...), and the fact that the actual content often remains small when icon size is increased (leaving absurd amounts of whitespace) are just some of the reasons why I generally prefer the thumbnail generation feature of `QLThumbnailImageCreate` :)

All feedback is very much appreciated! There are some bugs I want to fix/some refactoring I want to do first, but I'll try to implement all reasonable feature requests, so keep them coming! 👍 

(But a disclaimer: this is recreational/spare time programming, so updates will be somewhat infrequent. PRs are also always welcome) :)

`QLThumbnailImageCreate` takes a `CGSize` parameter (which, according to Apple's docs, is "A structure that contains width and height values") so I don't immediately know how to use a multiplier.

**Comment by cylott** [comment]
> The different icons depending on size, and the somewhat strange "effects" that are added to icons (page curls were hot... in the mid-90s...), and the fact that the actual content often remains small when icon size is increased (leaving absurd amounts of whitespace) are just some of the reasons why I generally prefer the thumbnail generation feature of QLThumbnailImageCreate :)

Agreed!

> All feedback is very much appreciated! There are some bugs I want to fix/some refactoring I want to do first, but I'll try to implement all reasonable feature requests, so keep them coming!

Thanks so much for the replies. I will try to tinker where I can, but as I'm primarily a PHP developer I'm a bit out of my depth!
